import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { writeFileSync, readFileSync } from 'fs'
import { resolve } from 'path'
import { fileURLToPath } from 'url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))

function configWriterPlugin() {
  return {
    name: 'config-writer',
    configureServer(server) {
      server.middlewares.use('/__config', (req, res) => {
        if (req.method !== 'POST') { res.statusCode = 405; res.end(); return; }
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
          try {
            const { supabaseUrl, supabaseAnonKey, phongId } = JSON.parse(body);
            const content = `// Auto-generated by Settings — chỉnh sửa qua giao diện Cài đặt\nexport const SUPABASE_URL      = ${JSON.stringify(supabaseUrl || '')};\nexport const SUPABASE_ANON_KEY = ${JSON.stringify(supabaseAnonKey || '')};\nexport const DEFAULT_PHONG_ID  = ${JSON.stringify(phongId || '')};\n`;
            writeFileSync(resolve(__dirname, 'src/config.js'), content, 'utf8');
            res.setHeader('Content-Type', 'application/json');
            res.end(JSON.stringify({ ok: true }));
          } catch (e) {
            res.statusCode = 500;
            res.end(JSON.stringify({ error: e.message }));
          }
        });
      });

      server.middlewares.use('/__initial', (req, res) => {
        if (req.method !== 'POST') { res.statusCode = 405; res.end(); return; }
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
          try {
            const { kpiLibrary, nhomLibrary, nvLibrary, nhomCvLibrary, kvLibrary, kpiListRefs, nhomListRefs } = JSON.parse(body);
            const filePath = resolve(__dirname, 'src/data/initialData.js');
            let content;
            try { content = readFileSync(filePath, 'utf8'); } catch { content = ''; }
            const now = new Date().toLocaleString('vi-VN');
            const fmt = v => JSON.stringify(v ?? [], null, 2);
            // Cập nhật dòng header comment
            content = content.replace(/^\/\/ Dữ liệu mặc định.*$/m, `// Dữ liệu mặc định — cập nhật lần cuối: ${now}`);
            // Thay thế hoặc thêm mới từng export const thư viện (không chạm các constant khác)
            const updateExport = (src, name, value) => {
              const marker = `export const ${name} =`;
              const start = src.indexOf(marker);
              if (start === -1) return src.trimEnd() + `\n\nexport const ${name} = ${fmt(value)};\n`;
              let i = start + marker.length;
              let depth = 0;
              while (i < src.length) {
                const c = src[i];
                if (c === '[' || c === '{') depth++;
                else if (c === ']' || c === '}') depth--;
                else if (c === ';' && depth <= 0) { i++; break; }
                i++;
              }
              return src.slice(0, start) + `export const ${name} = ${fmt(value)};` + src.slice(i);
            };
            const nhomCvNames = (nhomCvLibrary || []).filter(n => !n.archived_at).map(n => n.ten_nhom_cv);
            const kvNames     = (kvLibrary     || []).filter(n => !n.archived_at).map(n => n.ten_kv);
            content = updateExport(content, 'NHOM_CV_LIST',            nhomCvNames);
            content = updateExport(content, 'KHU_VUC_LIST',            kvNames);
            content = updateExport(content, 'INITIAL_KPI_LIST',        kpiListRefs  ?? []);
            content = updateExport(content, 'INITIAL_NHOM_LIST',       nhomListRefs ?? []);
            content = updateExport(content, 'INITIAL_KPI_LIBRARY',    kpiLibrary);
            content = updateExport(content, 'INITIAL_NHOM_LIBRARY',   nhomLibrary);
            content = updateExport(content, 'INITIAL_NHAN_VIEN',      nvLibrary);
            content = updateExport(content, 'INITIAL_NHOM_CV_LIBRARY', nhomCvLibrary);
            content = updateExport(content, 'INITIAL_KV_LIBRARY',     kvLibrary);
            writeFileSync(filePath, content, 'utf8');
            res.setHeader('Content-Type', 'application/json');
            res.end(JSON.stringify({ ok: true }));
          } catch (e) {
            res.statusCode = 500;
            res.end(JSON.stringify({ error: e.message }));
          }
        });
      });
    },
  };
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), configWriterPlugin()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/__tests__/setup.js'],
  },
})
