// Auto-generated by Settings — chỉnh sửa qua giao diện Cài đặt
export const SUPABASE_URL      = "https://tvmdjzmipkvrunawuaba.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2bWRqem1pcGt2cnVuYXd1YWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2Mzc5NzcsImV4cCI6MjA5NDIxMzk3N30.T55k7djxIIbR1N2Or_FJH89qhNCPWq_bwHPZKCn3djc";
export const DEFAULT_PHONG_ID  = "5c97af34-4b0d-4607-b5c5-a2c6888d46ae";
